import Head from 'next/head'
import { useState } from 'react'
import Cards from '../components/Cards'
import Hell from '../components/Hell'
import Pagination from '../components/Pagination'


export default function Home() {
  const [pag, setPag] = useState(0)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hell />
      <Pagination pag={pag} setPag={setPag}/>
      <Cards pag={pag} setPag={setPag} />
    </>
  )
}
